### ISSUE TITLE
Builds failing due to goreleaser deprecation/removal of `replacements` 

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/firefly-cli#249]
See https://goreleaser.com/deprecations/#archivesreplacements

As of June 6th 2023 `goreleaser` no longer supports `archives.replacements`, so the following is causing the `goreleaser` action to fail:

```
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      amd64: x86_64
```

with `line 31: field replacements not found in type config.Archive`
