### ISSUE TITLE
Fabconnect exited(1)

### ISSUE THREAD

**Issue by hectordufau** [hyperledger/firefly-cli#254]
After run **ff start <stack>**, setting connection profiles files and organization msp paths, I receive this message when command ends:
```
dependency failed to start: container teste_fabconnect_0 exited (1)
```
Before, this message appears:
```
Volume "teste_ipfs_data_0"  Created time="2023-09-01T15:16:28-03:00" level=warning msg="volume \"teste_dataexchange_0\" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume"
```
and this message appears on ipfs_0 container log:
```
2023-09-01T19:10:36.943Z ERROR cmd/ipfs ipfs/daemon.go:559 failed to bootstrap (no peers found): consider updating Bootstrap or Peering section of your config
```

I'm using latest Hyperledger Fabric version (2.5.4), Docker 24.0.5 and Ubuntu 22.04

ccp.yaml used:
```
certificateAuthorities:
  utah.teste.com:
    tlsCACerts:
      path: 
        /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/msp/tlscacerts/ca.crt
    url: https://ca.utah.teste.com:8154
    grpcOptions:
      ssl-target-name-override: utah.teste.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
channels:
  teste:
    orderers:
      - orderer.teste.com
    peers:
      peer1.utah.teste.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  BCCSP:
    security:
      default:
        provider: SW
      enabled: true
      hashAlgorithm: SHA2
      level: 256
      softVerify: true
  credentialStore:
    cryptoStore:
      path: 
        /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/msp
    path: 
      /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/msp
  cryptoconfig:
    path: 
      /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/msp
  logging:
    level: info
  organization: utah.teste.com
  tlsCerts:
    client:
      cert:
        path: 
          /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp/signcerts/cert.pem
      key:
        path: 
          /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp/keystore/814a397054822896c18fbe68cc552c59e44f7fb329b40a4852f87bb6041ff796_sk
orderers:
  orderer.teste.com:
    tlsCACerts:
      path: 
        /dockerfabricwizard/domains/teste.com/ordererOrganizations/orderer/tls/tlscacerts/tls-localhost-8054-caorderer-teste-com.pem
    url: grpcs://orderer.teste.com:7050
organizations:
  utah.teste.com:
    certificateAuthorities:
      - utah.teste.com
    cryptoPath: 
      /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/msp
    mspid: utahMSP
    peers:
      - peer1.utah.teste.com
peers:
  peer1.utah.teste.com:
    tlsCACerts:
      path: 
        /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/peer1.utah/tls/tlscacerts/tls-localhost-8154-ca-utah-teste-com.pem
    url: grpcs://peer1.utah.teste.com:7051
version: 1.1.0%
```

Prints below:
![image](https://github.com/hyperledger/firefly-cli/assets/12888215/f2b6b9f4-6f5e-4502-b794-cbfc404ae80f)
![image](https://github.com/hyperledger/firefly-cli/assets/12888215/b7ae1c8f-ad20-49ee-90e9-8b106cffe718)

**Comment by hectordufau** [comment]
After run ff again, I'd checked the logs by **ff logs** command, and I found this:
```
teste_fabconnect_0  | Error: User credentials store creation failed. Failed to load identity configurations: failed to create identity config from backends: failed to load client TLSConfig : failed to load client key: failed to load pem bytes from path /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp/keystore/c085b7edaebf70c3786a4d4ef56555d028bf7c51fdc2b0bab0a23d810fdea197_sk: open /dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp/keystore/c085b7edaebf70c3786a4d4ef56555d028bf7c51fdc2b0bab0a23d810fdea197_sk: no such file or directory
```

However _c085b7edaebf70c3786a4d4ef56555d028bf7c51fdc2b0bab0a23d810fdea197_sk_ file exists. I need to update manually docker-compose.yaml or it is a ff command bug because the msp Admin path doesn't found or mapped correctly?

**Comment by hectordufau** [comment]
Reading log I undestood that some crypto files needed to be placed on path mapped as /etc/firefly/organizations/ fabconnect container. After I changed ccp.yaml to use this path, because it uses paths inside of the container. That's ok until now.

However, firefly_core container doesn't run because it doesn't call firefly chaincode:
```
Failed to invoke chaincode channel=teste chaincode=firefly error="error in simulation: failed to execute transaction bc788480a7b8bd97e4fc063196fd43bff892488f50b6285b6f63861a8d499072: could not launch chaincode firefly_1:938ae10e06a27c7a6e7e1c09e3ae563b75affcf7b68fa4541d586e6d0ce0d292: connection to firefly_1:938ae10e06a27c7a6e7e1c09e3ae563b75affcf7b68fa4541d586e6d0ce0d292 failed: error cannot create connection for firefly_1:938ae10e06a27c7a6e7e1c09e3ae563b75affcf7b68fa4541d586e6d0ce0d292: error creating grpc connection to peer1utah_firefly_ccaas:9999: failed to create new connection: connection error: desc = \"transport: error while dialing: dial tcp 172.31.0.8:9999: connect: connection refused\""
```
I'm using chaincode as a service (peer1utah_firefly_ccaas container)
![image](https://github.com/hyperledger/firefly-cli/assets/12888215/8cd21abe-6251-47b0-b9ae-39182b8d9435)

**Comment by hectordufau** [comment]
External chaincode access checked by installing another chaincode (typescript basic asset), and it runs ok:
![image](https://github.com/hyperledger/firefly-cli/assets/12888215/4b7f6642-c401-4bd5-b4c3-030bed1c9165)
![image](https://github.com/hyperledger/firefly-cli/assets/12888215/13ec3680-9e8e-4ceb-8958-942775c1d06d)

**Comment by hectordufau** [comment]
Is required for external chaincode connection TLS enabled? How to do it for Firefly?

**Comment by hectordufau** [comment]
Even packaging firefly chaincode with TLS enabled, it happens the same
```
FF10284: Error from fabconnect: Transaction processing for endorser [peer1.utah.teste.com:7051]: Chaincode status Code: (500) UNKNOWN. Description: error in simulation: failed to execute transaction aadfd82335f0294e8ecfc973a373cc416de04a7799599c6bd9e63c9f3e24922c: could not launch chaincode firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f: connection to firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f failed: error cannot create connection for firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f: error creating grpc connection to peer1utah_firefly_ccaas:9999: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 172.31.0.8:9999: connect: connection refused"
```

**Comment by nguyer** [comment]
Hi @hectordufau. I am guessing from your fabconnect error log above that a volume is not getting mapped to the container correctly. You say `/dockerfabricwizard/domains/teste.com/peerOrganizations/utah/users/Admin@utah.teste.com/msp/keystore/c085b7edaebf70c3786a4d4ef56555d028bf7c51fdc2b0bab0a23d810fdea197_sk` exists, but does that full path exist inside your container, or on your host machine?

Have you made any edits to `docker-compose.override.yaml`? If so, can you please post those too so I can take a look?

I think you're following the tutorial in the docs to connect to the Fabric Test Network? If so, there is an important note that tutorial when you go to run `ff init` about what directory you are in before you run that command: https://hyperledger.github.io/firefly/tutorials/chains/fabric_test_network.html#create-the-firefly-stack

> **NOTE**: The following command should be run in the `test-network` directory as it includes a relative path to the `organizations` directory containing each org’s MSP

That may not be your problem, but it is definitely one way that you could end up in a situation where the crypto material did not get mapped to the fabconenct container correctly.

**Comment by hectordufau** [comment]
@nguyer really I've solved ccp yaml file problem already. I understood when I looked at another ccp file created using "default" init command. After reviews, fabconnect container runs ok.

However fabconnect doesn't connect to firefly chaincode container. I've packaged firefly chaincode for build an external chaincode service like described here: https://hyperledger-fabric.readthedocs.io/en/latest/cc_service.html

After firefly container starts, I get this messsage from peer:
 ´´´
FF10284: Error from fabconnect: Transaction processing for endorser [peer1.utah.teste.com:7051]: Chaincode status Code: (500) UNKNOWN. Description: error in simulation: failed to execute transaction aadfd82335f0294e8ecfc973a373cc416de04a7799599c6bd9e63c9f3e24922c: could not launch chaincode firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f: connection to firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f failed: error cannot create connection for firefly_1:217c2894c068d5aceecb14c0c3c9d4dcdff5fc595aed27a6118c46383e6c372f: error creating grpc connection to peer1utah_firefly_ccaas:9999: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 172.31.0.8:9999: connect: connection refused"
 ´´´
If I deploy another chaincode (typescript code for example), all things are going well below the sun...haha

Do you have any suggestion how to deploy firefly chaincode as a service?

**Comment by nguyer** [comment]
@jimthematrix may have deployed the FireFly chaincode as a service before and may have some suggestions? I have not myself though.

**Comment by hectordufau** [comment]
@jimthematrix would you like to send any suggestion?

**Comment by celiacheff** [comment]
Here's what I put in my docker-compose.override.yml, you can ignore the "image" lines, the important part is the extra_hosts, especially on the peer.
```yml
# Add custom config overrides here
# See https://docs.docker.com/compose/extends
version: "2.1"

services:
  fabric_orderer:
    image: hyperledger/fabric-orderer:2.5
  fabric_peer:
    image: hyperledger/fabric-peer:2.5
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fabconnect_0:
    image: ghcr.io/hyperledger/firefly-fabconnect:v0.9.17
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fabconnect_1:
    image: ghcr.io/hyperledger/firefly-fabconnect:v0.9.17
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fabconnect_2:
    image: ghcr.io/hyperledger/firefly-fabconnect:v0.9.17
    extra_hosts:
      - "host.docker.internal:host-gateway"
```
