### ISSUE TITLE
Generated config has mismatched hosts for some members

### ISSUE THREAD

**Issue by awrichar** [hyperledger/firefly-cli#94]
I just generated a 2 party stack (as part of running the firefly E2E tests), and some of the URLs in the config are mismatched. Notice in the file below, it is for `org_0` and points to `ipfs_0` and `dataexchange_0`, but also points to `ethconnect_1` and `tokens_1`. This causes some strange failures since certain actions go to the wrong container.

`firefly_core_0.yaml`
```yaml
log:
  level: debug
debug:
  port: 6060
http:
  port: 5000
  address: 0.0.0.0
  publicURL: http://127.0.0.1:5000
admin:
  port: 5101
  address: 0.0.0.0
  enabled: true
  preinit: true
  publicURL: http://127.0.0.1:5101
ui:
  path: ./frontend
node:
  name: node_0
org:
  name: org_0
  identity: 0xee08e985af4544e46dd735cf13080a39a8761146
blockchain:
  type: ethereum
  ethereum:
    ethconnect:
      url: http://ethconnect_1:8080
      instance: /contracts/firefly
      topic: "1"
database:
  type: sqlite3
  sqlite3:
    url: /etc/firefly/db?_busy_timeout=5000
    migrations:
      auto: true
publicstorage:
  type: ipfs
  ipfs:
    api:
      url: http://ipfs_0:5001
    gateway:
      url: http://ipfs_0:8080
dataexchange:
  https:
    url: http://dataexchange_0:3000
tokens:
- connector: https
  name: erc1155
  url: http://tokens_1:3000
```
